#!/bin/bash

IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
IP=${IP#addr:}

if [[ $HOSTNAME == "node"* ]] ; then
    #rightscale
    IP=$(grep $(hostname)_ext /etc/hosts | awk '{print $1}')
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    IP=localhost
fi

#cqlsh "$IP" -e << EOF
cqlsh "$IP" -e "
CREATE KEYSPACE recommendations WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
create table  if not exists recommendations.product
(product_class_id int,
product_id int PRIMARY KEY,
brand_name text,
product_name text,
sku bigint,
srp float,
gross_weight float,
net_weight float,
recyclable_package float,
low_fat float,
units_per_case float,
cases_per_pallet float,
shelf_width float,
shelf_height float,
shelf_depth float);
"
#EOF

cqlsh "$IP" -e "COPY recommendations.product FROM './product.csv' WITH HEADER = true;"
