#!/bin/bash

echo "running streaming job"
#build and run spark job
mvn package && nohup dse spark-submit --deploy-mode cluster --supervise  --class com.datastax.powertools.analytics.SparkMLProductRecommendationServeJDBC ./target/StreamingMLProductRecommendations-0.1.jar localhost 9999&
