#!/bin/bash

pwd
echo "running streaming job"
rm -rf ./target/*
#build and run spark job
mvn package; mvn package && nohup dse spark-submit --class com.datastax.powertools.analytics.SparkMLProductRecommendations target/StreamingMLProductRecommendations-0.1.jar localhost 9999&
